/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package message;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TSensorData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7745310425418103483L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TSensorData\",\"namespace\":\"message\",\"fields\":[{\"name\":\"measurement_time\",\"type\":\"long\"},{\"name\":\"device_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"temperature\",\"type\":[\"double\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public long measurement_time;
  @Deprecated public java.lang.String device_id;
  @Deprecated public java.lang.Double temperature;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TSensorData() {}

  /**
   * All-args constructor.
   * @param measurement_time The new value for measurement_time
   * @param device_id The new value for device_id
   * @param temperature The new value for temperature
   */
  public TSensorData(java.lang.Long measurement_time, java.lang.String device_id, java.lang.Double temperature) {
    this.measurement_time = measurement_time;
    this.device_id = device_id;
    this.temperature = temperature;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return measurement_time;
    case 1: return device_id;
    case 2: return temperature;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: measurement_time = (java.lang.Long)value$; break;
    case 1: device_id = (java.lang.String)value$; break;
    case 2: temperature = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'measurement_time' field.
   * @return The value of the 'measurement_time' field.
   */
  public java.lang.Long getMeasurementTime() {
    return measurement_time;
  }

  /**
   * Sets the value of the 'measurement_time' field.
   * @param value the value to set.
   */
  public void setMeasurementTime(java.lang.Long value) {
    this.measurement_time = value;
  }

  /**
   * Gets the value of the 'device_id' field.
   * @return The value of the 'device_id' field.
   */
  public java.lang.String getDeviceId() {
    return device_id;
  }

  /**
   * Sets the value of the 'device_id' field.
   * @param value the value to set.
   */
  public void setDeviceId(java.lang.String value) {
    this.device_id = value;
  }

  /**
   * Gets the value of the 'temperature' field.
   * @return The value of the 'temperature' field.
   */
  public java.lang.Double getTemperature() {
    return temperature;
  }

  /**
   * Sets the value of the 'temperature' field.
   * @param value the value to set.
   */
  public void setTemperature(java.lang.Double value) {
    this.temperature = value;
  }

  /**
   * Creates a new TSensorData RecordBuilder.
   * @return A new TSensorData RecordBuilder
   */
  public static message.TSensorData.Builder newBuilder() {
    return new message.TSensorData.Builder();
  }

  /**
   * Creates a new TSensorData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TSensorData RecordBuilder
   */
  public static message.TSensorData.Builder newBuilder(message.TSensorData.Builder other) {
    return new message.TSensorData.Builder(other);
  }

  /**
   * Creates a new TSensorData RecordBuilder by copying an existing TSensorData instance.
   * @param other The existing instance to copy.
   * @return A new TSensorData RecordBuilder
   */
  public static message.TSensorData.Builder newBuilder(message.TSensorData other) {
    return new message.TSensorData.Builder(other);
  }

  /**
   * RecordBuilder for TSensorData instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TSensorData>
    implements org.apache.avro.data.RecordBuilder<TSensorData> {

    private long measurement_time;
    private java.lang.String device_id;
    private java.lang.Double temperature;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(message.TSensorData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.measurement_time)) {
        this.measurement_time = data().deepCopy(fields()[0].schema(), other.measurement_time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.device_id)) {
        this.device_id = data().deepCopy(fields()[1].schema(), other.device_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.temperature)) {
        this.temperature = data().deepCopy(fields()[2].schema(), other.temperature);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing TSensorData instance
     * @param other The existing instance to copy.
     */
    private Builder(message.TSensorData other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.measurement_time)) {
        this.measurement_time = data().deepCopy(fields()[0].schema(), other.measurement_time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.device_id)) {
        this.device_id = data().deepCopy(fields()[1].schema(), other.device_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.temperature)) {
        this.temperature = data().deepCopy(fields()[2].schema(), other.temperature);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'measurement_time' field.
      * @return The value.
      */
    public java.lang.Long getMeasurementTime() {
      return measurement_time;
    }

    /**
      * Sets the value of the 'measurement_time' field.
      * @param value The value of 'measurement_time'.
      * @return This builder.
      */
    public message.TSensorData.Builder setMeasurementTime(long value) {
      validate(fields()[0], value);
      this.measurement_time = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'measurement_time' field has been set.
      * @return True if the 'measurement_time' field has been set, false otherwise.
      */
    public boolean hasMeasurementTime() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'measurement_time' field.
      * @return This builder.
      */
    public message.TSensorData.Builder clearMeasurementTime() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'device_id' field.
      * @return The value.
      */
    public java.lang.String getDeviceId() {
      return device_id;
    }

    /**
      * Sets the value of the 'device_id' field.
      * @param value The value of 'device_id'.
      * @return This builder.
      */
    public message.TSensorData.Builder setDeviceId(java.lang.String value) {
      validate(fields()[1], value);
      this.device_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'device_id' field has been set.
      * @return True if the 'device_id' field has been set, false otherwise.
      */
    public boolean hasDeviceId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'device_id' field.
      * @return This builder.
      */
    public message.TSensorData.Builder clearDeviceId() {
      device_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'temperature' field.
      * @return The value.
      */
    public java.lang.Double getTemperature() {
      return temperature;
    }

    /**
      * Sets the value of the 'temperature' field.
      * @param value The value of 'temperature'.
      * @return This builder.
      */
    public message.TSensorData.Builder setTemperature(java.lang.Double value) {
      validate(fields()[2], value);
      this.temperature = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'temperature' field has been set.
      * @return True if the 'temperature' field has been set, false otherwise.
      */
    public boolean hasTemperature() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'temperature' field.
      * @return This builder.
      */
    public message.TSensorData.Builder clearTemperature() {
      temperature = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public TSensorData build() {
      try {
        TSensorData record = new TSensorData();
        record.measurement_time = fieldSetFlags()[0] ? this.measurement_time : (java.lang.Long) defaultValue(fields()[0]);
        record.device_id = fieldSetFlags()[1] ? this.device_id : (java.lang.String) defaultValue(fields()[1]);
        record.temperature = fieldSetFlags()[2] ? this.temperature : (java.lang.Double) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
